services:
  - type: web
    name: growchatbot
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: MISTRAL_API_KEY
        sync: false